apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-seu-apim-config
  namespace: seu-apim
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "ea75c595-d978-4682-9f6d-612a014c68ba"
    keyvaultName: "aks-vault3e49"
    cloudName: "AzurePublicCloud"
    tenantId: "1f00763a-1f87-473b-bba1-b6c746af03e4"
    objects: |
      array:
        - |
          objectName: ejadah-password
          objectType: secret
        - |
          objectName: noordb-password
          objectType: secret
        - |
          objectName: banner-db-password
          objectType: secret
        - |
          objectName: django-secret-key
          objectType: secret
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: yaqeen-username
          objectType: secret
        - |
          objectName: yaqeen-password
          objectType: secret
        - |
          objectName: sms-gateway-key
          objectType: secret
        - |
          objectName: azure-openai-key
          objectType: secret
        - |
          objectName: ats-erp-test-api-key
          objectType: secret
        - |
          objectName: ats-erp-prod-api-key
          objectType: secret
          
  secretObjects:
  - data:
    - key: ejadah-password
      objectName: ejadah-password
    - key: noordb-password
      objectName: noordb-password
    - key: banner-db-password
      objectName: banner-db-password
    - key: django-secret-key
      objectName: django-secret-key
    - key: db-user
      objectName: db-user
    - key: db-password
      objectName: db-password
    - key: yaqeen-username
      objectName: yaqeen-username
    - key: yaqeen-password
      objectName: yaqeen-password
    - key: sms-gateway-key
      objectName: sms-gateway-key
    - key: azure-openai-key
      objectName: azure-openai-key
    - key: ats-erp-test-api-key
      objectName: ats-erp-test-api-key
    - key: ats-erp-prod-api-key
      objectName: ats-erp-prod-api-key
    secretName: azure-kv-seu-apim-config
    type: Opaque